name: note_book
description: A Flutter-based project, where you can keep all your notes and many other texts...
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  dartz: 
  equatable: 
  flutter_bloc: 
  go_router:
  get_it: 
  rxdart:  
  provider:
  path_provider:
  test: 
  flex_color_scheme:  
  flutter_platform_widgets:   
  meta: 
  hive_flutter:
  icons_launcher:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


fonts:
  - family: SFProText
    fonts:
      - asset: assets/fonts/SFProText/SF-Pro-Text-Thin.otf
        weight: 100
      - asset: assets/fonts/SFProText/SF-Pro-Text-Ultralight.otf
        weight: 200
      - asset: assets/fonts/SFProText/SF-Pro-Text-Light.otf
        weight: 300
      - asset: assets/fonts/SFProText/SF-Pro-Text-Regular.otf
        weight: 400
      - asset: assets/fonts/SFProText/SF-Pro-Text-Medium.otf
        weight: 500
      - asset: assets/fonts/SFProText/SF-Pro-Text-Semibold.otf
        weight: 600
      - asset: assets/fonts/SFProText/SF-Pro-Text-Bold.otf
        weight: 700
      - asset: assets/fonts/SFProText/SF-Pro-Text-Heavy.otf
        weight: 800
  - family: SFProTextItalic
    fonts:
      - asset: assets/fonts/SFProText/SF-Pro-Text-ThinItalic.otf
        weight: 100
      - asset: assets/fonts/SFProText/SF-Pro-Text-UltralightItalic.otf
        weight: 200
      - asset: assets/fonts/SFProText/SF-Pro-Text-LightItalic.otf
        weight: 300
      - asset: assets/fonts/SFProText/SF-Pro-Text-RegularItalic.otf
        weight: 400
      - asset: assets/fonts/SFProText/SF-Pro-Text-MediumItalic.otf
        weight: 500
      - asset: assets/fonts/SFProText/SF-Pro-Text-SemiboldItalic.otf
        weight: 600
      - asset: assets/fonts/SFProText/SF-Pro-Text-BoldItalic.otf
        weight: 700
      - asset: assets/fonts/SFProText/SF-Pro-Text-HeavyItalic.otf
        weight: 800   
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        weight: 100
      - asset: assets/fonts/Roboto/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto/Roboto-Black.ttf
        weight: 700
  - family: RobotoItalic
    fonts:
      - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
        weight: 100
      - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        weight: 300
      - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        weight: 400
      - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        weight: 500
      - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        weight: 700


icons_launcher:
  image_path: "assets/icons/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true